server:
  port: 8000
  servlet:
    context-path: /nanyahuayi
  tomcat:
    basedir: /deploy/tomcat

spring:
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  datasource: 
    url: jdbc:mysql://localhost:3306/nanya?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: NANyahuayi123,
    driver-class-name: com.mysql.jdbc.Driver
    # Druid连接池 提供统计监控信息
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    format_sql: true

logging: 
  config: classpath:logback-spring.xml

#定义图片基础目录、基础访问路径
image: 
  product: 
    base-directory: /usr/share/nginx/html/dist
    base-url: https://www.ailejia.club

wechat: 
  appId: wxa3a9cf2825b29135
  appSecret: 628f3d999cf43530818e2945136f41db
  mchId: 1531448031
  mchKey: 13685wyh13685wyh13685wyh13685wyh
  keyPath: /deploy/apiclient_cert.p12
  notifyUrl: https://www.ailejia.club/nanyahuayi/pay/callback

jwt:
  key: 001100110011